version: '3.5'

services:
     
     db:
       image: mariadb:10.3
       volumes:
          - "db_vol:/var/lib/mysql"
       environment:
          MYSQL_ROOT_PASSWORD: wordpress
          MYSQL_DATABASE: wordpress
          MYSQL_USER: wordpress
          MYSQL_PASSWORD: wordpress


     wordpress:
        depends_on:
          - db
        build: ./
        volumes:
          - "wp_vol:/var/www/wp-content"
        ports:
          - "80-85:80"
        environment:
           DB_HOST: db
           DB_PASSWORD: wordpress
           DB_NAME: wordpress
           DB_USER: wordpress
           WORDPRESS_SITE_URL: http://localhost
           FS_METHOD: direct





volumes:
    db_vol:
    wp_vol: 


networks:
     cnet:
        driver: bridge
        ipam:
           driver: default 
           config:
               - subnet: 30.0.0.0/24
